export * from "@/pages/home";
export * from "@/pages/profile";
export * from "@/pages/sign-in";
export * from "@/pages/sign-up";
export * from "@/pages/testimonial";
export * from "@/pages/contact";
export * from "@/pages/About";
export * from "@/pages/Pcounter";
export * from '@/pages/contact';